# Drone controller configurations
# If you are from team 2 you must changes the IDs to px4_5, px4_6 .... px4_9
px4_0:
  coordinate_system: "NED"
  offboard_mode: "position"
px4_1:
  coordinate_system: "NED"
  offboard_mode: "position"
px4_2:
  coordinate_system: "NED"
  offboard_mode: "position"
px4_3:
  coordinate_system: "NED"
  offboard_mode: "position"
px4_4:
  coordinate_system: "NED"
  offboard_mode: "position"