# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}
{
  "1":{
    "0":{
      x: 191,
      y: 19,
      yaw: 90},
    "1":{
      x: 193,
      y: 19,
      yaw: 90},
    "2":{
      x: 195,
      y: 19,
      yaw: 90},
    "3":{
      x: 197,
      y: 19,
      yaw: 90},
    "4":{
      x: 199,
      y: 19,
      yaw: 90},
  },
  "2":{
    "5":{
      x: 161,
      y: 430,
      yaw: 90},
    "6":{
      x: 163,
      y: 430,
      yaw: 90},
    "7":{
      x: 165,
      y: 430,
      yaw: 90},
    "8":{
      x: 167,
      y: 430,
      yaw: 90},
    "9":{
      x: 169,
      y: 430,
      yaw: 90},
  },
}
