# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}
{
  "1":{
    "0":{
      x: 71,
      y: 61,
      yaw: 90},
    "1":{
      x: 73,
      y: 61,
      yaw: 90},
    "2":{
      x: 75,
      y: 61,
      yaw: 90},
    "3":{
      x: 77,
      y: 61,
      yaw: 90},
    "4":{
      x: 79,
      y: 61,
      yaw: 90},
  },
  "2":{
    "5":{
      x: 139,
      y: 403,
      yaw: 90},
    "6":{
      x: 141,
      y: 403,
      yaw: 90},
    "7":{
      x: 143,
      y: 403,
      yaw: 90},
    "8":{
      x: 145,
      y: 403,
      yaw: 90},
    "9":{
      x: 147,
      y: 403,
      yaw: 90},
  },
}
