# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}
{
  "1":{
    "0":{
      x: 115,
      y: 49,
      yaw: 90},
    "1":{
      x: 117,
      y: 49,
      yaw: 90},
    "2":{
      x: 119,
      y: 49,
      yaw: 90},
    "3":{
      x: 121,
      y: 49,
      yaw: 90},
    "4":{
      x: 123,
      y: 49,
      yaw: 90},
  },
  "2":{
    "5":{
      x: 170,
      y: 416,
      yaw: 90},
    "6":{
      x: 172,
      y: 416,
      yaw: 90},
    "7":{
      x: 174,
      y: 416,
      yaw: 90},
    "8":{
      x: 176,
      y: 416,
      yaw: 90},
    "9":{
      x: 178,
      y: 416,
      yaw: 90},
  },
}
