# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}
{
  "1":{
    "0":{
      x: 93,
      y: 38,
      yaw: 90},
    "1":{
      x: 93,
      y: 38,
      yaw: 90},
    "2":{
      x: 95,
      y: 38,
      yaw: 90},
    "3":{
      x: 97,
      y: 38,
      yaw: 90},
    "4":{
      x: 99,
      y: 38,
      yaw: 90},
  },
  "2":{
    "5":{
      x: 30,
      y: 412,
      yaw: 90},
    "6":{
      x: 32,
      y: 412,
      yaw: 90},
    "7":{
      x: 34,
      y: 412,
      yaw: 90},
    "8":{
      x: 36,
      y: 412,
      yaw: 90},
    "9":{
      x: 38,
      y: 412,
      yaw: 90},
  },
}
