# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}
{
  "1":{
    "0":{
      x: 110,
      y: 52,
      yaw: 90},
    "1":{
      x: 110,
      y: 52,
      yaw: 90},
    "2":{
      x: 112,
      y: 52,
      yaw: 90},
    "3":{
      x: 114,
      y: 52,
      yaw: 90},
    "4":{
      x: 116,
      y: 52,
      yaw: 90},
  },
  "2":{
    "5":{
      x: 110,
      y: 442,
      yaw: 90},
    "6":{
      x: 112,
      y: 442,
      yaw: 90},
    "7":{
      x: 114,
      y: 442,
      yaw: 90},
    "8":{
      x: 116,
      y: 442,
      yaw: 90},
    "9":{
      x: 118,
      y: 442,
      yaw: 90},
  },
}
