# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}
{
  "1":{
    "0":{
      x: 0,
      y: 0,
      yaw: 90},
    "1":{
      x: 0,
      y: 0,
      yaw: 90},
    "2":{
      x: 0,
      y: 0,
      yaw: 90},
    "3":{
      x: 0,
      y: 0,
      yaw: 90},
    "4":{
      x: 0,
      y: 0,
      yaw: 90},
  },
  "2":{
    "5":{
      x: 0,
      y: 0,
      yaw: 90},
    "6":{
      x: 0,
      y: 0,
      yaw: 90},
    "7":{
      x: 0,
      y: 0,
      yaw: 90},
    "8":{
      x: 0,
      y: 0,
      yaw: 90},
    "9":{
      x: 0,
      y: 0,
      yaw: 90},
  },
}
