game_master_node:
  ros__parameters:
    use_sim_time: True
    # Detection ranges
    drone_detection_range: 137.0
    ship2ship_detection_range: 500.0
    ship2drone_detection_range: 162.0
    drone_communication_range: 144.0
    ship_communication_range: 525.0
    
    # Health and damage settings
    drone_health: 1
    ship_health: 6
    
    # Game rules
    game_duration: 300  # 5 minutes
    record_game_state: true
    
    # Gazebo configuration
    gazebo_world_name: "game_world_water"
    drone_model_base_name: "x500_lidar_front"
    
    # Missile system parameters
    drone_missile_range: 69.0
    ship_missile_range: 81.0
    drone_missile_damage: 1
    ship_missile_damage: 1
    drone_cooldown: 8.0
    ship_cooldown: 6.0
    drone_magazine: 2
    ship_magazine: 4
    laser_width: 4.0
    
    # Target size padding
    drone_padding_x: 0.5
    drone_padding_y: 0.5
    drone_padding_z: 0.5
    ship_padding_x: 6.0
    ship_padding_y: 1.0
    ship_padding_z: 1.0
    
    # Kamikaze parameters
    explosion_damage: 3
    explosion_range: 5.0